/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Personal
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainJFrame.class.getName());

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Principal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        registrarNuevoEvento = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        registrarEventoSimple = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        registrarEventoIntrusion1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        registrarEventoIntrusion2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        reporteBasico = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        reporteBasicoIntrusion = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        reporteDetallado = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        reporteDetalladoIntrusion = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        consultarInfo = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        MenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Principal.png"))); // NOI18N
        MenuPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 635));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Principal.png"))); // NOI18N

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PrincipalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PrincipalLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", Principal);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrarNuevoEvento.png"))); // NOI18N

        javax.swing.GroupLayout registrarNuevoEventoLayout = new javax.swing.GroupLayout(registrarNuevoEvento);
        registrarNuevoEvento.setLayout(registrarNuevoEventoLayout);
        registrarNuevoEventoLayout.setHorizontalGroup(
            registrarNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(registrarNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registrarNuevoEventoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        registrarNuevoEventoLayout.setVerticalGroup(
            registrarNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(registrarNuevoEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registrarNuevoEventoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", registrarNuevoEvento);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrarEventoSimple.png"))); // NOI18N

        javax.swing.GroupLayout registrarEventoSimpleLayout = new javax.swing.GroupLayout(registrarEventoSimple);
        registrarEventoSimple.setLayout(registrarEventoSimpleLayout);
        registrarEventoSimpleLayout.setHorizontalGroup(
            registrarEventoSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(registrarEventoSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registrarEventoSimpleLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        registrarEventoSimpleLayout.setVerticalGroup(
            registrarEventoSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(registrarEventoSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registrarEventoSimpleLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", registrarEventoSimple);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrarEventoIntrusion1.png"))); // NOI18N

        javax.swing.GroupLayout registrarEventoIntrusion1Layout = new javax.swing.GroupLayout(registrarEventoIntrusion1);
        registrarEventoIntrusion1.setLayout(registrarEventoIntrusion1Layout);
        registrarEventoIntrusion1Layout.setHorizontalGroup(
            registrarEventoIntrusion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(registrarEventoIntrusion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registrarEventoIntrusion1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        registrarEventoIntrusion1Layout.setVerticalGroup(
            registrarEventoIntrusion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(registrarEventoIntrusion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registrarEventoIntrusion1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", registrarEventoIntrusion1);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrarEventoIntrusion2.png"))); // NOI18N

        javax.swing.GroupLayout registrarEventoIntrusion2Layout = new javax.swing.GroupLayout(registrarEventoIntrusion2);
        registrarEventoIntrusion2.setLayout(registrarEventoIntrusion2Layout);
        registrarEventoIntrusion2Layout.setHorizontalGroup(
            registrarEventoIntrusion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(registrarEventoIntrusion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registrarEventoIntrusion2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        registrarEventoIntrusion2Layout.setVerticalGroup(
            registrarEventoIntrusion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(registrarEventoIntrusion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registrarEventoIntrusion2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", registrarEventoIntrusion2);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporteBasico.png"))); // NOI18N

        javax.swing.GroupLayout reporteBasicoLayout = new javax.swing.GroupLayout(reporteBasico);
        reporteBasico.setLayout(reporteBasicoLayout);
        reporteBasicoLayout.setHorizontalGroup(
            reporteBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(reporteBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reporteBasicoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        reporteBasicoLayout.setVerticalGroup(
            reporteBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(reporteBasicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reporteBasicoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", reporteBasico);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporteBasicoIntrusion.png"))); // NOI18N

        javax.swing.GroupLayout reporteBasicoIntrusionLayout = new javax.swing.GroupLayout(reporteBasicoIntrusion);
        reporteBasicoIntrusion.setLayout(reporteBasicoIntrusionLayout);
        reporteBasicoIntrusionLayout.setHorizontalGroup(
            reporteBasicoIntrusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(reporteBasicoIntrusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reporteBasicoIntrusionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        reporteBasicoIntrusionLayout.setVerticalGroup(
            reporteBasicoIntrusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(reporteBasicoIntrusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reporteBasicoIntrusionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", reporteBasicoIntrusion);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporteDetallado.png"))); // NOI18N

        javax.swing.GroupLayout reporteDetalladoLayout = new javax.swing.GroupLayout(reporteDetallado);
        reporteDetallado.setLayout(reporteDetalladoLayout);
        reporteDetalladoLayout.setHorizontalGroup(
            reporteDetalladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(reporteDetalladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reporteDetalladoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        reporteDetalladoLayout.setVerticalGroup(
            reporteDetalladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(reporteDetalladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reporteDetalladoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", reporteDetallado);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporteDetalladoIntrusion.png"))); // NOI18N

        javax.swing.GroupLayout reporteDetalladoIntrusionLayout = new javax.swing.GroupLayout(reporteDetalladoIntrusion);
        reporteDetalladoIntrusion.setLayout(reporteDetalladoIntrusionLayout);
        reporteDetalladoIntrusionLayout.setHorizontalGroup(
            reporteDetalladoIntrusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(reporteDetalladoIntrusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reporteDetalladoIntrusionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        reporteDetalladoIntrusionLayout.setVerticalGroup(
            reporteDetalladoIntrusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(reporteDetalladoIntrusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reporteDetalladoIntrusionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", reporteDetalladoIntrusion);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultarInfo.png"))); // NOI18N

        javax.swing.GroupLayout consultarInfoLayout = new javax.swing.GroupLayout(consultarInfo);
        consultarInfo.setLayout(consultarInfoLayout);
        consultarInfoLayout.setHorizontalGroup(
            consultarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(consultarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultarInfoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        consultarInfoLayout.setVerticalGroup(
            consultarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(consultarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultarInfoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", consultarInfo);

        MenuPrincipal.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -35, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MenuPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 210, 80));

        getContentPane().add(MenuPrincipal, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JPanel Principal;
    private javax.swing.JPanel consultarInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel registrarEventoIntrusion1;
    private javax.swing.JPanel registrarEventoIntrusion2;
    private javax.swing.JPanel registrarEventoSimple;
    private javax.swing.JPanel registrarNuevoEvento;
    private javax.swing.JPanel reporteBasico;
    private javax.swing.JPanel reporteBasicoIntrusion;
    private javax.swing.JPanel reporteDetallado;
    private javax.swing.JPanel reporteDetalladoIntrusion;
    // End of variables declaration//GEN-END:variables
}
